export const GET_TODO_START = 'GET_TODO_START'
export const GET_TODO_SUCCESS = 'GET_TODO_SUCCESS'
export const GET_TODO_FAILED = 'GET_TODO_FAILED'

export const CREATE_TODO_START = 'CREATE_TODO_START'
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS'
export const CREATE_TODO_FAILED = 'CREATE_TODO_FAILED'

export const DELETE_TODO_START = 'DELETE_TODO_START'
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS'
export const DELETE_TODO_FAILED = 'DELETE_TODO_FAILED'

export const UPDATE_TODO_START = 'UPDATE_TODO_START'
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS'
export const UPDATE_TODO_FAILED = 'UPDATE_TODO_FAILED'